"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fontCalculation = exports.percentageCalculation = exports.useTableView = exports.useResponsiveScreenFontSize = exports.useResponsiveScreenWidth = exports.useResponsiveScreenHeight = exports.useResponsiveFontSize = exports.useResponsiveWidth = exports.useResponsiveHeight = exports.useDeviceType = exports.useDimensionsListener = void 0;
var useDimensionsListener_1 = require("./hooks/useDimensionsListener");
Object.defineProperty(exports, "useDimensionsListener", { enumerable: true, get: function () { return useDimensionsListener_1.useDimensionsListener; } });
var useDeviceType_1 = require("./hooks/useDeviceType");
Object.defineProperty(exports, "useDeviceType", { enumerable: true, get: function () { return useDeviceType_1.useDeviceType; } });
var useResponsive_1 = require("./hooks/useResponsive");
Object.defineProperty(exports, "useResponsiveHeight", { enumerable: true, get: function () { return useResponsive_1.useResponsiveHeight; } });
Object.defineProperty(exports, "useResponsiveWidth", { enumerable: true, get: function () { return useResponsive_1.useResponsiveWidth; } });
Object.defineProperty(exports, "useResponsiveFontSize", { enumerable: true, get: function () { return useResponsive_1.useResponsiveFontSize; } });
Object.defineProperty(exports, "useResponsiveScreenHeight", { enumerable: true, get: function () { return useResponsive_1.useResponsiveScreenHeight; } });
Object.defineProperty(exports, "useResponsiveScreenWidth", { enumerable: true, get: function () { return useResponsive_1.useResponsiveScreenWidth; } });
Object.defineProperty(exports, "useResponsiveScreenFontSize", { enumerable: true, get: function () { return useResponsive_1.useResponsiveScreenFontSize; } });
var useTableView_1 = require("./hooks/useTableView");
Object.defineProperty(exports, "useTableView", { enumerable: true, get: function () { return useTableView_1.useTableView; } });
var calculations_1 = require("./utils/calculations");
Object.defineProperty(exports, "percentageCalculation", { enumerable: true, get: function () { return calculations_1.percentageCalculation; } });
Object.defineProperty(exports, "fontCalculation", { enumerable: true, get: function () { return calculations_1.fontCalculation; } });
//# sourceMappingURL=index.js.map